version: "3.9"
services:
  mysql-server:
    image: mysql:latest
    ports:
      - "3606:3606"
    container_name: mysql_container
    networks:
      - my-network
    environment:
      MYSQL_ROOT_PASSWORD: pass@123
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: pass@123
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  user-service:
    container_name: user-service
    build: ./
    networks:
      - my-network
    ports:
      - "65500:65500"
    depends_on:
      - mysql-server
    restart: always

networks:
  my-network:
    driver: bridge